config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/page.rb
class Page < ActiveRecord::Base
	def category_enum
		['networking','graphic designing']
	end
	validates :name, :title, :section, :category, :dscription, :section, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@pag=Page.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Topbrains</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><%=link_to "Home", root_path%></li>
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class=""><%=link_to "Admin", rails_admin_path%></li>
      </ul>
    </div>
  </div>
</nav>
<%@pag.each do |frm|%>
  <div style="border-color:#aabbcc; width:200;" >
  <p><%=frm.name%></p>
 <p> <%=frm.title%></p>
  <p><%=frm.dscription%></p>
<p><%=time_ago_in_words(frm.created_at,include_seconds: true)%> ago</p>

  <%end%>
  </div>